# Site wide configuration

title: "The HELP Project"
description: "A Community Project to model the health and economic impacts of different lockdown exit strategies"
logo: help_logo.png
teaser: 400x250.gif
locale: en_US
url: "https://auquan.github.io/help_project"
feed:
  path: atom.xml

# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

#Post Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false

# Site owner
owner:
  name: "HELP Project"
  web: "https://auquan.com"
  twitter: ""
  bio: ""
  avatar: "help_logo.png" # 160x160 px image for author byline
  google:
    plus: ""
    ad-client: ""
    ad-slot:
  disqus-shortname:

include: ["_pages"]
include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
